### ISSUE TITLE
Flatpak app

### ISSUE THREAD

**Issue by arun54321** [bkueng/qMasterPassword#21]
Could you release it on flathub?

**Comment by bkueng** [comment]
Can you create the build manifest, then I can do the release?

**Comment by stefanb2** [comment]
I guess we could start from [this](https://docs.flatpak.org/en/latest/qt.html), seems pretty simple.

The only real decision left would be what the application ID would be.

**Comment by bkueng** [comment]
It's now available: https://flathub.org/apps/io.github.bkueng.qMasterPassword

**Comment by stefanb2** [comment]
Maybe I'm  blind, but I can't see any build files for flatpak in the git repo. IMHO a GitHub workflow should be added for it.

**Comment by stefanb2** [comment]
I did a quick test and it seems that the flatpak app does not use the same location for the user data as a version installed from an OS package. I know that this should be possible, because I have seen it working for other flatpak apps.

This makes it easier for users to move to the flatpak version, f.ex. when a distro decides to drop the package,

**Comment by bkueng** [comment]
It's here: https://github.com/flathub/io.github.bkueng.qMasterPassword
